language: node_js
sudo: true
dist: trusty

node_js:
  - '5.6.0'

branches:
  only:
  - master

before_script:
- npm install -g angular-cli
- npm install -g karma
- ng build

script:
- ng test --single-run --code-coverage

after_script:
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js
