language: node_js
node_js:
  - "node"
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
